### ISSUE TITLE
Is there a way to load the xmind file ?

### ISSUE THREAD

**Issue by OriLiMu** [xmindltd/xmind-sdk-js#12]
Here is the thing I need a program to auto add image after I done with the xmind file without image. I may add some key word on the node which will be inserted with image. 

I check the example of the code seems no way to load a xmind file.  So I ask if there is a way to make it ? Thank you in advance.

**Comment by danielsss** [comment]
> Here is the thing I need a program to auto add image after I done with the xmind file without image. I may add some key word on the node which will be inserted with image.
> 
> I check the example of the code seems no way to load a xmind file. So I ask if there is a way to make it ? Thank you in advance.

In currently, you can't reload `.xmind` file with this SDK. the only way that is UI-Client.

**Comment by danielsss** [comment]
relates #17
