### ISSUE TITLE
0.5.0升级到2.2.0

### ISSUE THREAD

**Issue by wenhuichen** [xmindltd/xmind-sdk-js#22]
原先的  open: Workbook.open 方法没了，现在要读取xmind文件解析，要怎么读？

**Comment by danielsss** [comment]
你好，建议回滚至 0.5.0, 因为新版本目前暂不支持加载文件到 SDK，但后续会对此功能进行相关开发和支持。 参考 Issue: #20

**Comment by Yuzeyang** [comment]
读取已有文件应该是个强需求，希望尽快加上哈
