### ISSUE TITLE
example 中的示例无法运行，控制台无报错，界面无内容

### ISSUE THREAD

**Issue by thinkido** [xmindltd/xmind-sdk-js#28]
example.browser.html怎样才算正常运行了，可以给一些动态图或视频吗？

**Comment by thinkido** [comment]
看到控制台console.log有信息，应该是正常运行了。浏览器界面上不会显示内容吗？思维导图主要的就是界面

**Comment by thinkido** [comment]
我想要在浏览器上运行思维导图的界面，支持赞助118元。

**Comment by danielsss** [comment]
> 看到控制台console.log有信息，应该是正常运行了。浏览器界面上不会显示内容吗？思维导图主要的就是界面

@thinkido 你好，如果你想使用网页版的思维导图。可以推荐你访问：https://xmind.works 

不过目前只支持了美区用户（Beta Stage），你可以自行注册使用。

**Comment by danielsss** [comment]
> 我想要在浏览器上运行思维导图的界面，支持赞助118元。

@thinkido  SDK 目前仅支持生成客户端可用的代码包，暂时无法支持用户在浏览器中图形化开发。
