### ISSUE TITLE
怎么导出图像呢？

### ISSUE THREAD

**Issue by cheezone** [xmindltd/xmind-sdk-js#32]
我想要自动创建 XMind 文件并导出为图像，自动插入到我这边的工作流程里面，请问需要怎么做？如果不能在 SDK 里面完成，我的 XMind 已经开了会员了，请问有命令行什么的自动导出为图像吗？

**Comment by danielsss** [comment]
@cheezone 

> 我想要自动创建 XMind 文件并导出为图像，自动插入到我这边的工作流程里面，请问需要怎么做？

* 目前客户端暂时无法通过其他外部方式或自动将文件保存为图片（大部分客户端支持手动将编辑后的内容保存为图片）
* 因为前置条件目前无法满足，则自动插入工作流程的后置需求也无法满足

> 如果不能在 SDK 里面完成，我的 XMind 已经开了会员了，请问有命令行什么的自动导出为图像吗？

* 目前没有命令行可以自动导出为图片


##### 针对您提出的问题，我们会对此方面的需求进行内部沟通以及相关问题的推进。

**Comment by dimkua** [comment]
+1 ，我们也有这方面需求，希望可以通过sdk或者命令行导出未pdf或者图片

**Comment by danielsss** [comment]
> +1 ，我们也有这方面需求，希望可以通过sdk或者命令行导出未pdf或者图片

目前的话并没有特别好的方法，因为内部代码耦合性问题。为了解决这个问题，内部也正在重构并解耦。但需要一段时间。

可以通过 [Viewer](https://github.com/danielsss/embed-viewer) 生成 html，然后用 gh-page 或 gl-page 展示。生成图片暂时无法解决。
