### ISSUE TITLE
example下的example.browser.html没有效果

### ISSUE THREAD

**Issue by windyoung1990** [xmindltd/xmind-sdk-js#43]
问题：
1. 没看懂怎么使用的
2. example.browser.html打开没有内容，控制台无报错，有几行打印信息
感谢回复

**Comment by rockcitystore** [comment]
+1

**Comment by danielsss** [comment]
@rockcitystore SDK 的用途是生成一个文件，并不是将内容展示到页面。所以控制台输出的内容是可以保存为文件的。

**Comment by rockcitystore** [comment]
> 

谢谢 已经在node环境成功生成xmind文件了 不过功能和样式还是相对少了，期待完善。
