### ISSUE TITLE
style properties full list

### ISSUE THREAD

**Issue by JasonZough** [xmindltd/xmind-sdk-js#47]
Is there a way to find all style properties just like [theme files](https://github.com/xmindltd/xmind-sdk-js/blob/master/src/common/themes/business.json)?
Thanks a lot.
![image](https://user-images.githubusercontent.com/19682484/153567871-e574f074-7eb7-4e65-bd1a-ee4f160615c6.png)

**Comment by danielsss** [comment]
I think `workbook.toJSON()` is what you need.
