### ISSUE TITLE
Type 'null' is not assignable to type 'string'.

### ISSUE THREAD

**Issue by Johnboy-max** [xmindltd/xmind-sdk-js#49]
<img width="332" alt="image" src="https://user-images.githubusercontent.com/66511871/176385782-432c42e0-b9db-45f5-a6d0-9017d4723034.png">
<img width="358" alt="image" src="https://user-images.githubusercontent.com/66511871/176385846-de1cbe21-6a0e-4278-b44b-7d738a16bdac.png">

**Comment by danielsss** [comment]
What the problem is? Please, Could you paste more details about this error here or you can provide more narrating about it?

**Comment by Johnboy-max** [comment]
> What the problem is? Please, Could you paste more details about this error here or you can provide more narrating about it?
你在xmindltd/xmind-sdk-js/src/abstracts/topic.abstract.ts 这个抽象类里面定义的cid方法规定了返回值为string
在xmindltd/xmind-sdk-js/src/core/topic.ts 实现的地方这里的cid的返回值是string｜ null，编译的时候ts报错

**Comment by danielsss** [comment]
It has been fixed through a new release v2.2.25 and we appreciate that you prompted the feedback.
