### ISSUE TITLE
runtime-core.esm-bundler.js:218 Uncaught TypeError: Zipper is not a constructor

### ISSUE THREAD

**Issue by waters-souls** [xmindltd/xmind-sdk-js#56]
version 2.2.27
code:
import { Workbook, Topic, Marker, Zipper } from 'xmind';
const zip = new Zipper({path: 'D:/tmp', workbook: wb,filename:'MyFirstMap'});

**Comment by danielsss** [comment]
@waters-souls The `Zipper` object only works at the backend and You can use the `Dumper` object instead of it if you want.

**Comment by waters-souls** [comment]
> @waters-souls The `Zipper` object only works at the backend and You can use the `Dumper` object instead of it if you want.

Thank you！
