### ISSUE TITLE
How to generate xmind with json or array

### ISSUE THREAD

**Issue by Zaynex** [xmindltd/xmind-sdk-js#6]
If I have data like 
```
[
  {
    title: 'subtopic 1',
    submmary: 'summary'
  },
  {
    title: 'subtopic 2',
  },
  {
    title: 'subtopic 1'
  }
]
```

1. How can I use `xmind-sdk` to generate xmind file with array or json?
Now i am using the api like `add` and `summary`.Is there a simpler way to go directly convert xmind file?

2. How can I find the second `subtopic 1`

**Comment by danielsss** [comment]
@Zaynex  Sorry for the late response.

* In the current, we only support to add elements via APIs and we will think about this feature.

* Here's an example code to show you `how to find the topic`:

```js
const mainTopic1 = topic.add({title: 'main topic 1'}).cid() //or topic.cid('main topic 1')

const sameSubtopic1 = topic.on(mainTopic1).add({title: 'same subtopic 1'}).cid()
console.info('first:', sameSubtopic1)

const sameSubtopic2 = topic.add({title: 'same subtopic 1'}).cid()
console.info('second:', sameSubtopic2)
```

PS:

* We allow adding the same topic on the map, but we advise to avoid this.

* It returns the first one found if there is a duplicate topic when you call `.cid()` with title.

* You can also to save the IDs step by step as the above example code.
