### ISSUE TITLE
js 怎么解析xmind 文件

### ISSUE THREAD

**Issue by Anjing1993** [xmindltd/xmind-sdk-js#67]

**Comment by danielsss** [comment]
Relates to #20

**Comment by Anjing1993** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Anjing1993** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
