### ISSUE TITLE
It fails to open the zip file if there're some Chinese characters have been included

### ISSUE THREAD

**Issue by OnePsycho** [xmindltd/xmind-sdk-js#69]
![image](https://github.com/xmindltd/xmind-sdk-js/assets/43296632/d06a6718-2670-45bb-8b30-664ba48e57bc)

**Comment by danielsss** [comment]
@OnePsycho It relates to the character encoding issue and It'd be fixed with the next release.

Thanks for letting me know 😊.

**Comment by OnePsycho** [comment]
Hello, may I ask if the problem has been repaired ？

**Comment by danielsss** [comment]
> Hello, may I ask if the problem has been repaired ？

Yes, It has been fixed in [Release 2.2.29](https://github.com/xmindltd/xmind-sdk-js/releases/tag/v2.2.29)

**Comment by OnePsycho** [comment]
> > Hello, may I ask if the problem has been repaired ？
> 
> Yes, It has been fixed in [Release 2.2.29](https://github.com/xmindltd/xmind-sdk-js/releases/tag/v2.2.29)

But after I update to 2.2.29 did have a part of the problem before Chinese garbled can generate normal open part of the Chinese characters and the file can't open you can see the figure below

![image](https://github.com/xmindltd/xmind-sdk-js/assets/43296632/e75e0bed-2e77-4c0c-81a7-2818e5e3a53b)

![image](https://github.com/xmindltd/xmind-sdk-js/assets/43296632/ad9bd929-4ff6-46d6-af3d-414e60af0d26)

**Comment by OnePsycho** [comment]
Hello, may I ask if the problem has been repaired ？

**Comment by danielsss** [comment]
> Hello, may I ask if the problem has been repaired ？

@OnePsycho I didn't realize this issue which is hard to resolve. we use the `JSzip` as a compressor, but `JSzip` doesn't fully support characters for other languages.

So, I need to reconsider this issue, which might take some time.

> PR is also welcome

**Comment by danielsss** [comment]
@OnePsycho DO NOT close this issue until we move further.

~~I'm trying to add a workaround release for this issue.~~

I've released version `v2.2.30` with a quick fix. Please, chuck it back here if you've any issues.

<img width="344" alt="image" src="https://github.com/xmindltd/xmind-sdk-js/assets/5127897/bbba48ac-955f-4343-8101-e431ef59288f">

**Comment by OnePsycho** [comment]
ok i will try you solution soon

**Comment by danielsss** [comment]
> ok i will try you solution soon

This issue will be closed and you can reopen it any time if you have any problems.
