### ISSUE TITLE
[BUG]broswer使用插件时报错 Cannot find module './robust-fdb2b57a.json'

### ISSUE THREAD

**Issue by pengxx1758** [xmindltd/xmind-sdk-js#71]
出现背景：昨天使用 npm install 安装xmind,照示例简单使用一切正常，次日启动项目开发调试，编译阶段就报该错误。
报错如下：
![image](https://github.com/xmindltd/xmind-sdk-js/assets/38789049/0d665585-dd2f-4642-a1ed-77ac29f9a120)

Node版本：
![image](https://github.com/xmindltd/xmind-sdk-js/assets/38789049/95a1d610-514e-49a4-915a-a4f29ef7b7b2)

出现问题代码：
依赖，xmind版本 v2.2.29
![image](https://github.com/xmindltd/xmind-sdk-js/assets/38789049/611db86c-857a-4cfa-b52b-0fcb05250ad1)
使用
![image](https://github.com/xmindltd/xmind-sdk-js/assets/38789049/856462ef-049b-4427-8aac-e0134055b0b7)
代码在函数内，初始化未调用，在编译阶段红色的代码就已经报错了，注释或去掉代码后运行正常

尝试解决：
1、删除xmind依赖重新安装（未解决）
2、清除项目node_modules和lock，重新install（未解决）
3、怀疑杀毒软件将文件误删，但未见提示和记录（待定）

**Comment by pengxx1758** [comment]
补充报错如下：
![image](https://github.com/xmindltd/xmind-sdk-js/assets/38789049/10ca2680-0dc0-4d61-9516-384197913789)

**Comment by pengxx1758** [comment]
node版本：
![image](https://github.com/xmindltd/xmind-sdk-js/assets/38789049/6e7a5580-80ba-42f9-a50b-69a611df1411)

**Comment by danielsss** [comment]
@pengxx1758 robust-*.json 是一个皮肤配置文件，安装完成后应该在目录 node_modules/xmind/dist/common/themes/robust.json.

> 编译后的 js 文件应该是这样引用的 r.Theme=void 0;var i=e("../common/themes/robust.json")

> 可能需要你提供更详细的问题描述
