### ISSUE TITLE
Allow empty string as topic title

### ISSUE THREAD

**Issue by tomtiao** [xmindltd/xmind-sdk-js#81]
https://github.com/xmindltd/xmind-sdk-js/blob/29fddd5eb8064717dd9674cfe6dd690684b71b3c/src/core/topic.ts#L76

The `add` method of `Topic` prevents setting an empty string as a topic title, which should be valid in xmind.

**Comment by danielsss** [comment]
v2.2.31 has been released for this issue.

**Comment by tomtiao** [comment]
@danielsss Sorry to bother, but is v2.2.31 available on npm any time soon? I am still getting the same error using the latest package from npm. 

![image](https://github.com/xmindltd/xmind-sdk-js/assets/47553271/d05d43e8-ba5e-4e0e-980f-a624f838a5cf)

**Comment by danielsss** [comment]
@tomtiao I'm so sorry for this.

That was my fault. I've released a version that I forgot to build the codes.

Try: `npm i --save xmind@2.2.32` Let me know if you've any problems with this version or PRs are welcome.

**Comment by tomtiao** [comment]
> @tomtiao I'm so sorry for this.
> 
> That was my fault. I've released a version that I forgot to build the codes.
> 
> Try: `npm i --save xmind@2.2.32` Let me know if you've any problems with this version or PRs are welcome.

It works now. Thank you!
