### ISSUE TITLE
 是否已经适配了最新发版的引擎呢？

### ISSUE THREAD

**Issue by oqq5518** [xmindltd/xmind-sdk-js#84]

**Comment by danielsss** [comment]
1. 目前没有适配最新的引擎
2. #83 Zipper 用于后端，将.xmind文件保存至本地
3. #82 Dumper 用于前端，将编辑内容导出

**Comment by oqq5518** [comment]
请问它们的 github 地址可以发一下吗

**Comment by oqq5518** [comment]
有计划适配最新的引擎吗？

**Comment by danielsss** [comment]
> 请问它们的 github 地址可以发一下吗

新版本引擎目前并未开源

> 有计划适配最新的引擎吗？

因为内部主导方向不在此方面且个人也比较忙。所以暂时没有此计划。
