### ISSUE TITLE
如果用第三方的库实现对 xmind 文件的编辑，会违规吗？

### ISSUE THREAD

**Issue by oqq5518** [xmindltd/xmind-sdk-js#85]
比如像这个库：https://github.com/tobyqin/xmindparser
可以实现导入 xmind，解析，用这个 sdk编辑 xmind 数据，再导出 xmind。

**Comment by danielsss** [comment]
都开始开源库，不存在违规行为。 鼓励你使用其他库导入，但是不保证导入后会有丢失内容的问题。

**Comment by oqq5518** [comment]
我一个是导入 xmind 数据，一个是自己生成 xmind 文件，但是没有用到付费功能点。不只是导入。这样是官方鼓励的行为吗
